version: 2

jobs:
  build:
    docker:
      - image: alpine:latest

    steps:
      - checkout
      - run:
          name: Setup SSH Key
          command: |
            mkdir ~/.ssh/ && echo $SSH_KEY > ~/.ssh/deploy.key
            chmod 400 ~/.ssh/deploy.key
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              apk update
              apk add openssh

              echo "
                cd '$DEPLOY_DIR' && \
                git pull origin '${DEPLOY_BRANCH}' && \
                touch deploy.sh && sh deploy.sh
              " > script.sh

              IP_LIST=$(echo $IPS | tr "," "\n")
              for ip in $IP_LIST
              do
                echo "Deploy to ${ip}"
                ssh -i ~/.ssh/deploy.key $SSH_USER@$ip 'bash -s' < script.sh
              done
            else
              echo "NOT deploy to ${DEPLOY_BRANCH}"
            fi
